-- AlterTable
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "estimatedTimeMinutes" INTEGER,
ADD COLUMN IF NOT EXISTS "isRecurring" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "recurringPattern" TEXT,
ADD COLUMN IF NOT EXISTS "recurringEndDate" TEXT,
ADD COLUMN IF NOT EXISTS "parentRideId" INTEGER,
ADD COLUMN IF NOT EXISTS "isDraft" BOOLEAN NOT NULL DEFAULT false;

-- AddForeignKey
ALTER TABLE "rides" ADD CONSTRAINT "rides_parentRideId_fkey" FOREIGN KEY ("parentRideId") REFERENCES "rides"("id") ON DELETE SET NULL ON UPDATE CASCADE;

